### ISSUE TITLE
Translations in VIS - words.js file not found

### ISSUE THREAD

**Issue by klein0r** [ioBroker/create-adapter#503] opened 2020-05-15 07:15 UTC
After creating a new adapter, I get 404 errors for the `words.js`. What is the intended behavior here? Should there exist a seperate words.js for VIS? When using the admin words.js file, VIS has the problem that the translations will be overridden (since systemDictionary is reassigned).

https://github.com/ioBroker/create-adapter/blob/ddecd0ffbf297848b0199c5dfe0a12d16cbdb6af/templates/widgets/template.js.ts#L21-L25

My approach would be:

1. Put a separate words.json in the widget folder
2. Load that file
3. Remove the "substring magic" from the js file

**Comment by AlCalzone** [comment] 2020-05-15 08:02
I think this is a duplicate of https://github.com/ioBroker/create-adapter/issues/303

We never found a solution for that and I'm not using VIS. So if you have an idea, please let me know.
All I need to know is how the js-file must look like - I can do the TypeScript and template stuff :)

**Comment by klein0r** [comment] 2020-05-15 08:06
I've talked with Bluefox about this topic. His recommendation was to avoid loading an external translation file. When the load process takes too long, the interface is already built and the translations are missing. The most secure way is to init everything inline and remove the get request.

e.g.

```
// add translations for edit mode
$.extend(
    true,
    systemDictionary,
    {
        "size": {
            "en": "Size",
            "de": "Größe",
            "ru": "Размер",
            "pt": "Tamanho",
            "nl": "Grootte",
            "fr": "Taille",
            "it": "Dimensione",
            "es": "Talla",
            "pl": "Rozmiar",
            "zh-cn": "尺寸"
        }
    }
);
```

**Closed as completed** 2020-05-31 07:03 UTC
